# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password12345
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  messager_server:
    image: s1pepega/my_messager:0.0.1-SNAPSHOT
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://db:3306/mymessager?useSSL=false",
        "spring.datasource.username" : "serverUser",
        "spring.datasource.password" : "s1pepega"
      }'